In [433]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from time import sleep, time 
from selenium.common.exceptions import StaleElementReferenceException
import pandas as pd

In [434]:
navigateur = webdriver.Firefox()

# Partie 1 : Scrapping

## Récupération des données

In [435]:
navigateur.get('https://www.vinted.fr/')

In [436]:
navigateur.switch_to.window(navigateur.window_handles[0])
search=navigateur.find_element_by_id("search_text")
search.send_keys("chaussures")
search.send_keys(Keys.RETURN)

In [ ]:
carac=[]
navigateur.switch_to.window(navigateur.window_handles[0])
n = 1
while n < 400:
    navigateur.switch_to.window(navigateur.window_handles[0])
    pagesuivante=navigateur.find_element_by_class_name("Pagination_next__DUhdH")
    page=pagesuivante.get_attribute("href")
    navigateur.execute_script("window.open('')")
    navigateur.switch_to.window(navigateur.window_handles[1])
    navigateur.get(page)
    Re=navigateur.find_elements_by_class_name("ItemBox_overlay__1kNfX")
    navigateur.switch_to.window(navigateur.window_handles[0])
    navigateur.close()
    navigateur.switch_to.window(navigateur.window_handles[0])
    for i in range (len(Re)):
        lien=Re[i].get_attribute("href")
        navigateur.execute_script("window.open('')")
        navigateur.switch_to.window(navigateur.window_handles[1])
        navigateur.get(lien)
        details=navigateur.find_elements_by_class_name("details-list")
        title=navigateur.find_elements_by_class_name('details-list__item-title')
        item=navigateur.find_elements_by_class_name("details-list__item-value")

        if title[0].text=='MARQUE':
            marque=item[0].text
        else: 
            marque="NA"
        if title[1].text=='TAILLE':
            taille=item[1].text
        else:
            taille="NA"
        if title[2].text=='ÉTAT':
            état=item[2].text
        else:
            état="NA"
        if title[3].text=='COULEUR':
            couleur=item[3].text
        else:
            couleur="NA"
        if title[4].text=='EMPLACEMENT':
            emplacement=item[4].text
        else:
            emplacement="NA"
        if title[5].text=='MODES DE PAIEMENT':
            Modepaiement=item[5].text
        else:
            Modepaiement="NA"
        if title[6].text=='NOMBRE DE VUES':
            Vus=item[6].text
        else:
            Vus="NA"
        try:
            if title[7].text=='INTÉRESSÉS·ÉES':
                interet=item[7].text
        except:
            interet="NA"
        try:
            if title[8].text=='AJOUTÉ':
                ajout=item[8].text
        except: 
                try:
                    ajout=item[7].text
                except:
                    ajout=item[6].text

        a=navigateur.find_elements_by_class_name("breadcrumbs__item")
        genre=a[1].find_element_by_tag_name("span").text
        b=navigateur.find_element_by_class_name("c-text--heading")
        prix=b.text

        Resultat={"Marque":marque,"Taille":taille,"État":état,"Couleur":couleur,
                  "Emplacement":emplacement,"Modepaiement":Modepaiement,
                  "Nombre de vus":Vus,"interet":interet,"ajout":ajout,
                  "genre":genre,"prix":prix}
        carac.append(Resultat)

        navigateur.close()

        navigateur.switch_to.window(navigateur.window_handles[0])
    n=n+1

## Création de la base de données

In [488]:
Data1=pd.DataFrame(carac)

In [489]:
Data1.to_csv("Data_1_Vinted.csv")

In [490]:
Data1

,Marque,Taille,État,Couleur,Emplacement,Modepaiement,Nombre de vus,interet,ajout,genre,prix
0,ALEXANDER MCQUEEN,38,NEUF AVEC ÉTIQUETTE,"ROUGE, BLANC","GIGNAC-LA-NERTHE, FRANCE","CARTE BANCAIRE, PAYPAL",1,1 UTILISATEUR,IL Y A 42 MINUTES,Femmes,"350,00 €"
1,MELLOW YELLOW,38,NEUF SANS ÉTIQUETTE,"DORÉ, BORDEAUX","PLÉBOULLE, FRANCE","CARTE BANCAIRE, PAYPAL",1,1 UTILISATEUR,IL Y A 7 MINUTES,Femmes,"51,00 €"
2,NIKE,38.5,NEUF AVEC ÉTIQUETTE,ROSE,"AVIGNON, FRANCE","CARTE BANCAIRE, PAYPAL",1,1 UTILISATEUR,IL Y A 7 MINUTES,Femmes,"36,00 €"
3,NIKE,39,NEUF AVEC ÉTIQUETTE,"NOIR, BLANC","RUEIL-MALMAISON, FRANCE","CARTE BANCAIRE, PAYPAL",7,1 UTILISATEUR,IL Y A 10 HEURES,Femmes,"79,00 €"
4,THE KOOPLES,37,TRÈS BON ÉTAT,NOIR,"PARIS, FRANCE","CARTE BANCAIRE, PAYPAL",1,1 UTILISATEUR,IL Y A UNE HEURE,Femmes,"65,00 €"
...,...,...,...,...,...,...,...,...,...,...,...
3426,DSQUARED2,37,BON ÉTAT,"BLANC, ARGENTÉ","TOULON, FRANCE","CARTE BANCAIRE, PAYPAL",172,2 UTILISATEURS,IL Y A 3 MOIS,Femmes,"110,00 €"
3427,KICKERS,38,TRÈS BON ÉTAT,NOIR,"RIEUMES, FRANCE","CARTE BANCAIRE, PAYPAL",365,4 UTILISATEURS,IL Y A 15 JOURS,Femmes,"60,00 €"
3428,KICKERS,37.5,TRÈS BON ÉTAT,"ROSE, ROSE","RIEUMES, FRANCE","CARTE BANCAIRE, PAYPAL",71,4 UTILISATEURS,IL Y A 12 JOURS,Femmes,"58,00 €"
3429,KICKERS,39,BON ÉTAT,"GRIS, MARINE","RIEUMES, FRANCE","CARTE BANCAIRE, PAYPAL",1229,5 UTILISATEURS,IL Y A 2 MOIS,Femmes,"50,00 €"
3430,KICKERS,39,BON ÉTAT,BEIGE,"RIEUMES, FRANCE","CARTE BANCAIRE, PAYPAL",763,2 UTILISATEURS,IL Y A UN MOIS,Femmes,"50,00 €"